### ISSUE TITLE
Pod with resource limit fails to start with CAA

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/cloud-api-adaptor#745] opened 2023-03-24 21:23 UTC
A pod with `resources.limits.memory` cannot be started by kata when using CAA. The pod stays stuck in the `ContainerCreating` state. I think it is listed here: https://github.com/confidential-containers/cloud-api-adaptor/issues/127.

Containerd logs of the worker node show the following warnings:

```console
# journalctl -fu containerd
...
Mar 23 19:52:11 aks-nodepool1-20397562-vmss000000 kata[237257]: time="2023-03-23T19:52:11.56262176Z" level=warning msg="Large hotplug. Adding 0 MB of 1408 total memory" name=containerd-shim-v2 pid=237257 sandbox=a60db52445bafb6827d343cd67dc17bc18e468df324dee98fe0b03b4df3ff7b4 source=virtcontainers subsystem=sandbox
Mar 23 19:52:11 aks-nodepool1-20397562-vmss000000 kata[237257]: time="2023-03-23T19:52:11.565319855Z" level=warning msg="Large hotplug. Adding 0 MB of 1408 total memory" name=containerd-shim-v2 pid=237257 sandbox=a60db52445bafb6827d343cd67dc17bc18e468df324dee98fe0b03b4df3ff7b4 source=virtcontainers subsystem=sandbox
^C
```

Sampele pod config:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      runtimeClassName: kata
      nodeName:
      containers:
      - name: nginx
        image: bitnami/nginx:1.14
        resources:
          limits:
           memory: 1408Mi
        ports:
        - containerPort: 80
        imagePullPolicy: Always
```

If we can get the `GetTotalMemoryMB` to report the actual value in the CAA's case then we won't end up in this endless for loop:

https://github.com/kata-containers/kata-containers/blob/bbc699ddd890b6c34dbeddc8ad352322bd669bb3/src/runtime/virtcontainers/sandbox.go#L2096-L2111

I can use deploy CAA with webhoook that will strip out the memory limit from the pod spec. But I think it can be fixed in kata too.

**Comment by bpradipt** [comment] 2023-03-25 05:13
For kata remote hypervisor implementation, the hotplug operations should be a noop ideally.
cc @yoheiueda

**Comment by yoheiueda** [comment] 2023-03-27 05:30
When I created the patches for the PR to Kata, I put `panic` in operations in order to identify operations that are actually used by remote hypervisor. 

https://github.com/kata-containers/kata-containers/pull/3697/files#diff-efc34dcef49ec850fe20fe169f23692e4aa21ed0ab227462047a2c79e412c252R184-R210

@bpradipt do you think we can remove all of panic calls in the `remoteHypervisor` methods, or we should only update the hotplug operations only?

**Comment by bpradipt** [comment] 2023-03-28 05:06
@yoheiueda  based on the scope of remoteHypervisor I really don't think we need to implement hotplug especially for cpu/mem as the cpu/mem will always be tied to the pod VM instance size. 

I'm wondering if it makes sense to just log and return instead of `panic`. Wdyt ?

**Comment by yoheiueda** [comment] 2023-03-28 08:01
@bpradipt OK, I'll prepare a PR for Kata to make those functions noop.

panic was convenient for me to implement the initial patch, but I don't think is is necessary for now.

**Comment by yoheiueda** [comment] 2023-03-30 15:48
@bpradipt It looks like the problem is not due to panic.

The cause is that the `GetTotalMemoryMB` method always returns 0.
https://github.com/kata-containers/kata-containers/blob/4c810c7933a1ef044eca4cc31d1e90e79df6ac61/src/runtime/virtcontainers/remote.go#L217-L219

I noticed that we can avoid this problem by enabling Static Sandbox Resource Management https://github.com/kata-containers/kata-containers/commit/8cde54131af6f036e390e7cf8a44c9b8d70d2ff8.

https://github.com/kata-containers/kata-containers/blob/4c810c7933a1ef044eca4cc31d1e90e79df6ac61/src/runtime/virtcontainers/sandbox.go#L2045-L2047

We can enable the feature by editing `/etc/kata-containers/configuration.toml` so that the `[runtime]` section has `static_sandbox_resource_mgmt=true` like this.
```
[runtime]
static_sandbox_resource_mgmt=true
```

@surajssd  could you confrim that this setting fixes your problem?

If it is OK, I'll submit a PR to change the default value for the remote hypervisor.

**Comment by surajssd** [comment] 2023-04-04 03:12
> @surajssd  could you confrim that this setting fixes your problem?

I can confirm that when I added `static_sandbox_resource_mgmt=true` under `[runtime]` section of the `/opt/confidential-containers/share/defaults/kata-containers/configuration.toml` config file and started container with the above mentioned configuration things worked without issue. 

Thanks for that discovery @yoheiueda!

**Comment by yoheiueda** [comment] 2023-04-06 07:59
I raised a PR in kata conatiners for this problem.
https://github.com/kata-containers/kata-containers/pull/6617

**Comment by yoheiueda** [comment] 2023-04-12 14:43
https://github.com/kata-containers/kata-containers/pull/6617 has been merged.

I'll submit a PR to update the kata configuration in this repository.

**Closed** 2023-04-13 22:14 UTC
Labels: bug
