### ISSUE TITLE
Secret mount path gets sealed  in CAA logs

### ISSUE THREAD

**Issue by sudharshanibm3** [confidential-containers/cloud-api-adaptor#1424] opened 2023-09-11 11:12 UTC
## Description
While creating peer pods with configmap and secret mounts, the secret mount path gets sealed in CAA log
For example:
If we create a secret mount path with `/etc/secret`, the path gets sealed in CAA logs `/sealed/etc/secret`

```
2023/09/11 08:25:06 [adaptor/proxy]         destination:/etc/config source:/run/kata-containers/shared/containers/27265f3638f3f47f01451b217b41438939fbca7efdcaadf9df41260f5112c693-a094d1bc86f04bd8-config type:bind
2023/09/11 08:25:06 [adaptor/proxy]         destination:/sealed/etc/secret source:/run/kata-containers/shared/containers/27265f3638f3f47f01451b217b41438939fbca7efdcaadf9df41260f5112c693-4585b5f70e45b219-secret type:bind
```

**Comment by stevenhorsman** [comment] 2023-09-11 12:12
@arronwy @Xynnn007 - hey Arron & Ding, I was wondering if this behaviour is what you'd except to see here - that unsealed secrets have ended up with in the `sealed` directory as I would hope that the user experience for non-sealed secrets?
I'll note that we don't have the CDH built into peer pods and we aren't completely up to data with the attestation-agent at the moment incase that makes a difference?

@sudharshanibm3 could you post the secret yaml that you are using here in case it is helpful. If we can reproduce this in non-peer pods `CCv0` kata-containers that would also be a great data point.

**Comment by sudharshanibm3** [comment] 2023-09-11 12:15
Hi @stevenhorsman ,
Here is the yaml file I created for creating configmap and secrets with PodVM - https://gist.github.com/sudharshanibm3/bae5a2e0026c5dfa57e4b97ab3356b75

**Comment by arronwy** [comment] 2023-09-11 13:28
> I'll note that we don't have the CDH built into peer pods and we aren't completely up to data with the attestation-agent at the moment incase that makes a difference?

Hi @stevenhorsman  @sudharshanibm3 Yes, in CoCo runtime, if sealed secrets feature is enabled, it will auto prefix '/sealed' in secrets related mount path:
https://github.com/kata-containers/kata-containers/blob/CCv0/src/runtime/virtcontainers/kata_agent.go#L914

This will auto removed after unseal operation: 
https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/rpc.rs#L231
https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/cdh.rs#L135

If CDH is not integrated into the rootfs, can you have a try to disable sealed secret feature in the kata config file :
```
sealed_secret_enabled = false 
```
Since we enable it for all cc runtime by default:
https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh#L273

**Comment by stevenhorsman** [comment] 2023-09-11 13:35
> If CDH is not integrated into the rootfs, can you have a try to disable sealed secret feature in the kata config file :
> 
> ```
> sealed_secret_enabled = false 
> ```
> 
> Since we enable it for all cc runtime by default: https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh#L273

Great, thanks for the info Arron!

**Comment by arronwy** [comment] 2023-09-11 15:09
> > If CDH is not integrated into the rootfs, can you have a try to disable sealed secret feature in the kata config file :
> > ```
> > sealed_secret_enabled = false 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since we enable it for all cc runtime by default: https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh#L273
> 
> Great, thanks for the info Arron!
> 
> > This will auto removed after unseal operation:
> > https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/rpc.rs#L231
> > https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/cdh.rs#L135
> 
> Just to check - if we have the CDH installed then the unseal should happen (even when the secrets are not 'sealed'/encrypted) and go back to the original mount point?

Yes, we need CDH installed and kata-agent build with sealed-secret support: https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh#L231

Sealed secret will support both sealed and unsealed/common secrets and will go back to original after processed by kata-agent.

**Comment by yoheiueda** [comment] 2023-09-12 06:36
@stevenhorsman Do we need to disable the feature in our VM image? Or, we just need to use the consistent version pair of kata-shim and kata-agent to fix the reported error?

> Sealed secret will support both sealed and unsealed/common secrets and will go back to original after processed by kata-agent.

@bpradipt implemented dynamic updates of ConfigMap/Secrets for peer pod VMs. kata-agent does not support dynamic updates of Secrets right now, so dynamic updates of Secrets will not work with the feature, while dynamic updates of ConfigMap will still work.

https://github.com/confidential-containers/cloud-api-adaptor/issues/574
https://github.com/kata-containers/kata-containers/pull/6342
https://github.com/kata-containers/kata-containers/pull/7570#issuecomment-1675830115

**Comment by stevenhorsman** [comment] 2023-09-12 08:13
> @stevenhorsman Do we need to disable the feature in our VM image? Or, we just need to use the consistent version pair of kata-shim and kata-agent to fix the reported error?

I think the general community's input is that we need to resolve this by adding the CDH and rest-api-server to our peer pod VM as people want to use sealed secrets.

Thanks for raising the issue of dynamic update of secrets though, that's something we need to think more about.

**Comment by stevenhorsman** [comment] 2023-09-14 14:37
@arronwy @Xynnn007 (or anyone else more knowledgable than me!) - I was wondering if you could help me with some issues with cdh starting on the peer pod. When starting CDH we get:
```
/usr/local/bin/confidential-data-hub
Error: init Hub failed: kbs client creation failed: Kbs client error: no `agent.aa_kbc_params` provided in kernel commandline!
```

In peer pods we don't pass agent config via the command line, but just via the agent-config.toml. Is there any support for this in the confidential data hub?

**Comment by Xynnn007** [comment] 2023-09-14 19:32
> @arronwy @Xynnn007 (or anyone else more knowledgable than me!) - I was wondering if you could help me with some issues with cdh starting on the peer pod. When starting CDH we get:
> ```
> /usr/local/bin/confidential-data-hub
> Error: init Hub failed: kbs client creation failed: Kbs client error: no `agent.aa_kbc_params` provided in kernel commandline!
> ```
> 
> In peer pods we don't pass agent config via the command line, but just via the agent-config.toml. Is there any support for this in the confidential data hub?

Oh, could you provide more information about the agent-config.toml?

As the error told, CDH currently only supports to read aa_params from the kernel cmdline, which seems to need some update now.

**Comment by stevenhorsman** [comment] 2023-09-15 08:25
> Oh, could you provide more information about the agent-config.toml?

The agent-config.toml is a way to get the agent configuration from a file on the 'guest image' without going through kernel_params. It is currently the only way to restrict endpoints and used to be the only way to pass aa_kbc_params, so we use it quite a bit on our test files. https://github.com/kata-containers/kata-containers/blob/CCv0/tools/osbuilder/rootfs-builder/agent-config.toml.in is an example of the format and https://github.com/kata-containers/kata-containers/blob/ee15a389de021acf2de96e372761dd6271212c16/src/agent/src/config.rs#L420-L429 is where we process it. By convention the file is in `/etc/agent-config.toml`, but when starting the kata-agent we specify this with the `--config` option e.g https://github.com/confidential-containers/cloud-api-adaptor/blob/816b76ae831b7c9e13cdbfc4c56f7c652f6f590a/podvm/files/etc/systemd/system/kata-agent.service#L8C8-L8C9

**Comment by stevenhorsman** [comment] 2023-09-15 09:12
BTW as Suraj points out we are also hitting:
```
Sep 15 02:40:48 podvm-nginx-secret-pod-eb58589a systemd[1]: Started CDH API Server Rest Service.
Sep 15 02:40:48 podvm-nginx-secret-pod-eb58589a api-server-rest[1363]: Starting API server on 127.0.0.1:8006 with features all
Sep 15 02:40:48 podvm-nginx-secret-pod-eb58589a api-server-rest[1363]: Error: Nix error: ENOENT: No such file or directory
Sep 15 02:40:48 podvm-nginx-secret-pod-eb58589a api-server-rest[1363]: Caused by:
Sep 15 02:40:48 podvm-nginx-secret-pod-eb58589a api-server-rest[1363]:     ENOENT: No such file or directory
Sep 15 02:40:48 podvm-nginx-secret-pod-eb58589a systemd[1]: api-server-rest.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 02:40:48 podvm-nginx-secret-pod-eb58589a systemd[1]: api-server-rest.service: Failed with result 'exit-code'.
Sep 15 02:40:49 podvm-nginx-secret-pod-eb58589a systemd[1]: api-server-rest.service: Scheduled restart job, restart counter is at 5.
Sep 15 02:40:49 podvm-nginx-secret-pod-eb58589a systemd[1]: Stopped CDH API Server Rest Service.
Sep 15 02:40:49 podvm-nginx-secret-pod-eb58589a systemd[1]: api-server-rest.service: Start request repeated too quickly.
Sep 15 02:40:49 podvm-nginx-secret-pod-eb58589a systemd[1]: api-server-rest.service: Failed with result 'exit-code'.
Sep 15 02:40:49 podvm-nginx-secret-pod-eb58589a systemd[1]: Failed to start CDH API Server Rest Service.
```
when starting the api-server-rest. I was hoping it was related to the cdh not starting, but it's definitely worth pointing out now incase it is unrelated

**Comment by fitzthum** [comment] 2023-09-15 17:23
Some features of the CDH, such as sealed secrets of type `envelope` will require more configuration than can be provided via AA_KBC_PARAMS. There are some extra arguments added to the kernel command line to setup the credentials for connecting to a KMS, for instance. We are likely to refine this configuration in the future. For now you might be able to get away without it.

Can I ask how this agent-config file gets into the guest image? I was glancing at @bpradipt's https://github.com/confidential-containers/cloud-api-adaptor/pull/1440 and I realized I don't understand some of these mechanisms at all (maybe that is totally separate).

**Comment by stevenhorsman** [comment] 2023-09-15 17:30
We provide a static agent-config.toml in the podvm build: https://github.com/confidential-containers/cloud-api-adaptor/blob/main/podvm/files/etc/agent-config.toml, but we also have the ability to pass some more dynamic setting via user-data and Pradipta has also been working on a way to get that from the metadata service as well.

**Comment by bpradipt** [comment] 2023-09-17 06:01
Currently none of these configurations are measured. This is TBD along with policy integration.

**Comment by Xynnn007** [comment] 2023-09-17 06:51
> We provide a static agent-config.toml in the podvm build: https://github.com/confidential-containers/cloud-api-adaptor/blob/main/podvm/files/etc/agent-config.toml, but we also have the ability to pass some more dynamic setting via user-data and Pradipta has also been working on a way to get that from the metadata service as well.

Sry I'm not quite familiar with CAA. Is the following right?

The agent-config.toml can be either static in the podvm image or dynamic. If it is dynamic, it is fetched from the metadata service of the cloud service and then put to `daemon-config-path` (by default `/peerpod/daemon.json`).

If so, I think we can add a feature or just a condition code in CDH for CAA which will do the following:
- if `/peerpod/daemon.json` exists, CDH will read `aa_params` from that file instead of from kernel commandline.

How about that?

**Comment by stevenhorsman** [comment] 2023-09-17 08:19
> > We provide a static agent-config.toml in the podvm build: https://github.com/confidential-containers/cloud-api-adaptor/blob/main/podvm/files/etc/agent-config.toml, but we also have the ability to pass some more dynamic setting via user-data and Pradipta has also been working on a way to get that from the metadata service as well.
> 
> Sry I'm not quite familiar with CAA. Is the following right?
> 
> The agent-config.toml can be either static in the podvm image or dynamic. If it is dynamic, it is fetched from the metadata service of the cloud service and then put to `daemon-config-path` (by default `/peerpod/daemon.json`).
> 
> If so, I think we can add a feature or just a condition code in CDH for CAA which will do the following:
> 
> * if `/peerpod/daemon.json` exists, CDH will read `aa_params` from that file instead of from kernel commandline.
> 
> How about that?

I think that's nearly right, but `/peerpod/daemon.json` mostly has CAA specific config, so we still write to `/etc/agent-config.toml` with the `aa_kbc_params = ""` value. For 0.8 we could hard-code search for `/peerpod/daemon.json` existence (to see if we are in a peer-pod) and if so read `aa_kbc_params = ""` from`/etc/agent-config.toml`, then I think that should work correctly. I wonder if the best solution longer-term, rather than hard-coding is to add a `--config` option to CDH to specify the config.toml path to read it from like the kata-agent does, but I'm aware that policy might be replacing some of the functionality, so I don't want us to invest too much in that before then.

I'd definitely like to hear input from others if they think the workaround is correct and acceptable for this release?

**Comment by arronwy** [comment] 2023-09-18 06:49
yes, we will finally switch to integrity protected policy or init data for these configs, it's ok from my side to use this workaround as tmp solution for this release.

**Comment by stevenhorsman** [comment] 2023-09-21 09:22
Ok, so I think I've resolved the issue with reading aa_kbc_params from kernel command line in https://github.com/confidential-containers/guest-components/pull/365. Testing a peer pod created with that branch I now get:
```
# /usr/local/bin/confidential-data-hub
Error: init Hub failed: kbs client creation failed: Kbs client error: offline-fs-kbc: read /etc/aa-offline_fs_kbc-keys.json failed: No such file or directory (os error 2)
```
We don't have any encryption keys we are using, so this file doesn't exist. I guess there are a couple of things we could do here:
1. Just add a dummy `{}` content `/etc/aa-offline_fs_kbc-keys.json` file in the peer pod
2. Update cdh/AA? to make reading that file optional?

I'm interested in how this works on our local hypervisor tests too as we don't have `/etc/aa-offline_fs_kbc-keys.json` by default in our guest image either?

**Comment by Xynnn007** [comment] 2023-09-21 09:35
@stevenhorsman 
Could you show the building command for CDH?

The code assumes the `/etc/aa-offline_fs_kbc-keys.json` exists if we neither enable feature `kbs` nor `sev` for CDH.

**Comment by stevenhorsman** [comment] 2023-09-21 09:46
Yeah, the build is done in: 
https://github.com/stevenhorsman/cloud-api-adaptor/blob/bec529cfc809b999960bda50bd35f696f4a332b3/podvm/Makefile.inc#L152-L155
```
cd "$(GUEST_COMPONENTS_SRC)/confidential-data-hub" && CC= ARCH=$(ARCH) $(MAKE) RESOURCE_PROVIDER="$(CDH_RESOURCE_PROVIDER)" LIBC="$(LIBC)"
```
where `CDH_RESOURCE_PROVIDER ?= kbs`

I tried to match the approach used in rootfs.sh, but maybe made a mistake?

**Comment by stevenhorsman** [comment] 2023-09-21 14:56
Ok, I've also added a blank `/etc/aa-offline_fs_kbc-keys.json` file into the podvm and now the confidential-data-hub and api-server-rest systemd services are started:
```
# systemctl status confidential-data-hub.service
● confidential-data-hub.service - Confidential Data Hub Service
     Loaded: loaded (/etc/systemd/system/confidential-data-hub.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-09-21 14:50:21 UTC; 2min 55s ago
   Main PID: 833 (confidential-da)
      Tasks: 3 (limit: 9610)
     Memory: 6.7M
     CGroup: /system.slice/confidential-data-hub.service
             └─833 /usr/local/bin/confidential-data-hub

Sep 21 14:50:21 podvm-smur-executor-11062080 systemd[1]: Started Confidential Data Hub Service.
```

```
# systemctl status api-server-rest.service
● api-server-rest.service - CDH API Server Rest Service
     Loaded: loaded (/etc/systemd/system/api-server-rest.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-09-21 14:50:21 UTC; 4min 28s ago
   Main PID: 865 (api-server-rest)
      Tasks: 3 (limit: 9610)
     Memory: 704.0K
     CGroup: /system.slice/api-server-rest.service
             └─865 /usr/local/bin/api-server-rest --features all

Sep 21 14:50:21 podvm-smur-executor-11062080 systemd[1]: Started CDH API Server Rest Service.
Sep 21 14:50:21 podvm-smur-executor-11062080 api-server-rest[865]: Starting API server on 127.0.0.1:8006 with features all
Sep 21 14:50:21 podvm-smur-executor-11062080 api-server-rest[865]: API Server listening on http://127.0.0.1:8006
```

but the secrets are still not unsealed:
```
# kubectl exec smur-executor -- cat /etc/secret/username
cat: /etc/secret/username: No such file or directory
command terminated with exit code 1
# kubectl exec smur-executor -- cat /sealed/etc/secret/username
adminroot
```

**Comment by stevenhorsman** [comment] 2023-09-21 15:04
Oh - hang on a second - I'm not sure we've enabled the `sealed-secret` feature in our kata-agent build, so I'll check & try that first.

**Comment by stevenhorsman** [comment] 2023-09-21 16:06
I think I've fixed it with the sealed-secret feature:
```
# kubectl exec smur-executor -- cat /sealed/etc/secret/username
cat: /sealed/etc/secret/username: No such file or directory
command terminated with exit code 1
root@sh-pp-e2e1:~/go/src/github.com/confidential-containers/cloud-api-adaptor# kubectl exec smur-executor -- cat /etc/secret/username
adminroot@sh-pp-e2e1:~/go/src/github.com/confidential-containers/cloud-api-adaptor
```

Just need to wait for the guest-components to be merged

**Closed** 2023-09-25 08:04 UTC
