### ISSUE TITLE
ci: Start thinking about CI/CD options for the cloud-api-adaptor/peer-pods solution

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#16] opened 2022-05-12 17:18 UTC
This is (initially at least), not going to be a proper plan, but just a braindump of some things related to CI/CD that we might have to think of, please feel free to add any thoughts or suggestion directly to the description, or as comments.

We've already hit a few occasions when code changes to enable/improve one of the CSP implementations has broken one of the others, so it's definitely something we are going to want to think about sooner, rather than later to avoid regressions and/or lots of manual testing.

- The big obstacle (which I don't think we want to solve here, but will hopefully soon come out of some of the community release discussions) is where confidential-containers CI/CD will run in general. Up until now we've been running any CI and testing on the [kata-containers jenkins](http://jenkins.katacontainers.io/) as the jobs are all versions of existing kata ones, but I'm not sure if that will be the case for the cloud-api-adaptor code. I'm wondering if we can get GHA workflows for some of the build and test steps in the short term and avoid having to have dedicated servers?
- The different providers are a challenge as already have AWS and IBM Cloud implementations that would require access to accounts in order to test, which cost money. I'm not sure if we already have access to these anywhere that we can use? The other option we might want to take is use the libvirt support in open source and then leave the other provider testing to be done in house based on that?
- Work a proper build process. At the moment, the IBM Cloud provider implementation (the only one I've personally tried) has some [documentation](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/ibmcloud/README.md) available, but the process is still a PoC where the custom peer pod VM image is created on the test worker node and then pushed to IBM Cloud and the components required on the worker node to get peer-pods working (`cloud-api-adaptor`, `kata-shim` confidential-containerd fork of `containerd` are all built and installed directly on the worker). I think we probably want to separate out the build of the peer pod VM image (I think Pradipta has created https://github.com/confidential-containers/cloud-api-adaptor/issues/6 that covers the AWS equivalent of this?) and the `cloud-api-adaptor` binary as separate build artefacts?
- Work out a 'deployment' strategy. If we build the artefacts independently of the test environment we'll want to install them into a Kubernetes cluster (maybe using a single-node cluster like the Kata pipeline does?) I think this is something that we can use an extension of the coco-operator to do?

I'm sure there are other things that I've not thought of now and it's probably quite IBM Cloud centric, but @bpradipt and @wainersm please feel free to chip in your experience with CI/CD, the other providers and the operator

**Comment by wainersm** [comment] 2022-05-17 21:13
> This is (initially at least), not going to be a proper plan, but just a braindump of some things related to CI/CD that we might have to think of, please feel free to add any thoughts or suggestion directly to the description, or as comments.
> 

@stevenhorsman , thanks for starting this discussion.

> We've already hit a few occasions when code changes to enable/improve one of the CSP implementations has broken one of the others, so it's definitely something we are going to want to think about sooner, rather than later to avoid regressions and/or lots of manual testing.
>

Most of those regressions could be avoided by building for all the providers? Or caught only by e2e tests?
 
>     * The big obstacle (which I don't think we want to solve here, but will hopefully soon come out of some of the community release discussions) is where confidential-containers CI/CD will run in general. Up until now we've been running any CI and testing on the [kata-containers jenkins](http://jenkins.katacontainers.io/) as the jobs are all versions of existing kata ones, but I'm not sure if that will be the case for the cloud-api-adaptor code. I'm wondering if we can get GHA workflows for some of the build and test steps in the short term and avoid having to have dedicated servers?
>

I don' t believe the CoCo projects will be broadly leveraging Kata's Jenkins to run their CI/CD as we will need a more scalable and complex CI system due the nature of the projects. So I've spent the last couple of days investigating what could be used instead.

Kubernetes developed its own CI/CD (named [Prow](https://github.com/kubernetes/test-infra/tree/master/prow)) which is itself a Kubernetes based CI system. Prow was meant to be reused, the prove is that some big CNCF sponsored projects also used it, for example, Kubevirt and CRI-O. The entire CI of Red Hat's OpenShift is based on Prow.

Prow was also design to handle "umbrella projects"  like CoCo, which spans across several Github organizations and repositories. It provides:
 * CI/CD jobs execution with dashboard 
 * Github bot automation (reach to commands, e.g., "/lgtm", "/test" etc...)
 * Github merge automation (once requirements are met, the PR is automatically merged)
 * Automatic GitHub org/repo administration

That said and based on what I've seen, I strongly advocate for the use of Prow on CoCo. Of course there are many matters to be discussed but I don't want to bring it up right now and here to avoid deviating the main focus of this discussion.

I said that CRI-O leverages Prow. Actually its CI is a mix of Github actions for basic checks (build checks, static code checks, run unit tests, and so on) and Prow hooks for running e2e tests. The CRI-O CI, via Prow, does even trigger a job on Kata's Jenkins!

I like that approach took by CRI-O. Maybe we should be using Github actions for basic build and unit checks, I can be working on that right away. In mind and long term, we try to adopt Prow as self-hosted solution or/and get onboard on existing prow systems (more about it below). 
  
>     * The different providers are a challenge as already have AWS and IBM Cloud implementations that would require access to accounts in order to test, which cost money. I'm not sure if we already have access to these anywhere that we can use? The other option we might want to take is use the libvirt support in open source and then leave the other provider testing to be done in house based on that?
> 

I mentioned that OpenShift CI was built upon Prow. It provides test workflows where you can easily run your custom e2e tests on cloud providers, including aws, ibmcloud and even libvirt. Projects outside of the OpenShift organization can request to get onboard into OpenShift.

I got Kata Containers on-boarded there and I maintain daily jobs that run e2e tests on Azure. Similarly I could be working to onboard cloud-api-adaptor there so that getting access to clusters on those providers is straightforward. However, there are downsides on that, I will mention only two: 1) we will be testing on OpenShift rather than on a "pure"  Kubernetes installation, in a CI which is not controlled by CoCo community; 2) I don't now if other (or all) projects under CoCo umbrella will be able to get onboard, thus it is a solution which still keeps the CoCo' s CI fragmented.

All in all, we should consider that approach, maybe for the mid term, than replace it if needed by self-hosted Prow managed by the CoCo community.   

>     * Work a proper build process. At the moment, the IBM Cloud provider implementation (the only one I've personally tried) has some [documentation](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/ibmcloud/README.md) available, but the process is still a PoC where the custom peer pod VM image is created on the test worker node and then pushed to IBM Cloud and the components required on the worker node to get peer-pods working (`cloud-api-adaptor`, `kata-shim` confidential-containerd fork of `containerd` are all built and installed directly on the worker). I think we probably want to separate out the build of the peer pod VM image (I think Pradipta has created [Automated tooling to create AWS AMI image with kata-agent and dependencies #6](https://github.com/confidential-containers/cloud-api-adaptor/issues/6) that covers the AWS equivalent of this?) and the `cloud-api-adaptor` binary as separate build artefacts?
> 

Oh yeah, when you get into the technical details things get scarier.

Above I mentioned it is straightforward to get access to clusters on providers on OpenShift CI, however replace the runtime isn't so simple (although CRI-O manages to do that). Ah, made me remember that a solution based on OpenShift CI will be unlikely to allow us test with containerd.

To be honest, I still didn't stop to think about the build process as a whole.  

>     * Work out a 'deployment' strategy. If we build the artefacts independently of the test environment we'll want to install them into a Kubernetes cluster (maybe using a single-node cluster like the Kata pipeline does?) I think this is something that we can use an extension of the coco-operator to do?
> 

Good point. Also here I need to think about.
> 
> I'm sure there are other things that I've not thought of now and it's probably quite IBM Cloud centric, but @bpradipt and @wainersm please feel free to chip in your experience with CI/CD, the other providers and the operator

**Comment by stevenhorsman** [comment] 2022-05-18 08:35
@wainersm - thanks very much for your input. Prow isn't something that I know about, but it sounds decent. From my interpretation of your comments I think that discussion might be one to have at the broader CoCo level and then fit the cloud-api-adaptor into the overall strategy, and if so it might be good to get something scheduled on a community call to share this?

> > We've already hit a few occasions when code changes to enable/improve one of the CSP implementations has broken one of the others, so it's definitely something we are going to want to think about sooner, rather than later to avoid regressions and/or lots of manual testing.
> 
> Most of those regressions could be avoided by building for all the providers? Or caught only by e2e tests?

The issues that I've seen result in problems when trying to run the container on the peer pod. The peer pod VM is created, but due to incompatibility in versions of the cloud-api-adaptor, the kata-shim/agent and containerd they can never connect. Hopefully we won't regularly hit these, but from what I've seen they would only be detected with e2e tests as they are integration issues between separately built components

**Comment by ariel-adam** [comment] 2022-10-11 13:12
@stevenhorsman is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by ariel-adam** [comment] 2022-10-11 13:13
@stevenhorsman is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by stevenhorsman** [comment] 2022-10-11 13:14
This is still relevant. As it is an investigation task I think we want to address this in the mid-November timeframe, even if the only outcome is that we create a bunch of issue for later releases.

**Comment by ariel-adam** [comment] 2022-10-11 14:04
Mapped it to the CoCo releases project drop V.0.2.0 priority medium

**Comment by wainersm** [comment] 2022-10-11 14:09
btw, I've my focus on peer-pods now. Yesterday I was learning what would be the theoretical CI pipeline. I will be pasting that and some other ideas on this issue.

**Comment by wainersm** [comment] 2022-10-13 17:47
Hi @stevenhorsman , I've struggled to come up with a plan to the peer pods CI as this will be a really complex system.

I thought on tackle that with an bottom-up and practical approach:
 1) Understand the step-by-step to build and install peer pods
 2) Asses which building blocks we already have and which ones we will need to create. For example, ibmcloud has already terraforms to builds a demo that could be re-used on CI; whereas AWS has practically none upstream (@abhbaner has https://github.com/abhbaner/peer-pods-automation that we will be merging on)
 3) Create the missing building blocks
 4) Somehow wire those in a cohesive workflow that could be executed from our local machines. At this point, let's not discuss "how" and/or "where" the CI jobs properly saying should be ran

What do you think? Is there any better approach for this CI problem?

**Comment by wainersm** [comment] 2022-10-26 19:22
> I think that's the best approach and similar to the approach that I was discussing with @jtumber-ibm the other day:
> 
> > We can try and sync stages and maybe re-use some components then as well. e.g. I could imagine we have a separate ‘create cluster’ step, but then a ‘shared’ deploy operator and test it (albeit with different config) stage.
> > If you want to have a meeting to discuss it, or get us to share more of what we have then please shout!

Hi @stevenhorsman @jtumber-ibm , I finally found some time to put some ideas I have in paper (actually in code). My intent is to have something concrete to start with, then we can evolve ideas/improvements along the way.

Let me start with the layout of directories and files as it gives the big picture view:
```shell
$ pwd
/home/wmoschet/go/src/github.com/confidential-containers/cloud-api-adaptor/tests/e2e
$ tree
.
├── aws
│   └── pipeline_impl.sh
├── ibmcloud
│   ├── pipeline_impl.sh
│   └── terraform.tfvars.in
├── images
│   └── Dockerfile.runner
├── run-docker.sh
└── run-local.sh

3 directories, 6 files
```

Explaining each of those files:

* **run-local.sh** - the entry point script that glue stuffs to run the entire workflow. It run on local machine, in the sense that it expect dependencies (e.g. terraform) installed locally. We run it like `CLOUD_PROVIDER=ibmcloud ./run-local.sh`
* **run-docker.sh** - is a wrapper  to call `run-local.sh` inside the container so that we don't need to install dependencies on local machine. The `Dockerfile/Dockerfile.runner` is used to build the container image, it will have instructions to, for example, install terraform. Honestly, run-docker.sh is not important at this point and we can live without it, so I will ignore further details.
* **ibmcloud/pipeline_impl.sh** - implement the workflow for ibmcloud. It has methods and environment variables that are sourced in the `run-local.sh` script. 
* **ibmcloud/terraform.tfvars.in** - is just a specific file needed by the ibmcloud implementation. It is a template with the required terraform parameters.
* **aws/pipeline_impl.sh** - likewise for aws. You got the idea, right?

Let's have a look at `run-local.sh` (see the code below). The idea is:
* it sources `${CLOUD_PROVIDER}/pipeline_impl.sh`
* in `${CLOUD_PROVIDER}/pipeline_impl.sh` is defined
  * `REQ_COMMANDS` variable: list of commands needed to run the pipeline (e.g. terraform). Don't expect an extensive list of coreutils commands, but only those you don't find by default on the distros.
  * `REQ_ENVVARS` variable: list of environment variables that should be exported by the user. Environment variables are the way to pass parameters to the pipeline. I envision the CI exporting those variables accordingly. I don't know how to treat optional variables, if we even need to treat them.
  * `pipeline_setup()` method:  use to additional setup of the environment before running the pipeline steps.
  * `step_vpc_create()` method: implement the VPC creation for the `CLOUD_PROVIDER`
  *  `step_cluster_create()` method: likewise, create the k8s cluster. Maybe this is a step that can be shared amongst the cloud providers
  * `step_install()` method: or something similar that installs the operator. At this point I don't know if it will be implemented on each and every cloud provider implementation, or if we can have something shared as well. More steps to come. I decided to not to go further before sharing this with you, I am worried about "no, this whole thing makes no sense" and I waste time. 
 * ``pipeline_teardown()` method: execute on the exit of `run-local.sh`, probably the last thing to be ran. Can be used to delete the VPC after use, for example.

```bash
#!/bin/bash
# Use this script to run the end-to-end tests locally.
#
set -o errexit
set -o nounset
set -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly project_dir="$(cd "${script_dir}/../../" && pwd)"

CLOUD_PROVIDER="${CLOUD_PROVIDER:-}"

# Check that all commands required to run the pipeline are installed.
#
# Read from REQ_COMMANDS that should be exported by the pipeline implementation.
check_commands() {
	for cmd in $REQ_COMMANDS; do
		if ! command -v "$cmd" >/dev/null; then
			echo "ERROR: command '$cmd' not found"
			return 1
		fi
	done
}

# Check that all environment variables required to run the pipeline are
# exported.
#
# Read from REQ_ENVVARS that should be exported by the pipeline implementation.
check_envvars() {
	for var in $REQ_ENVVARS; do
		if eval "[ -z \${${var}+x} ]"; then
			echo "ERROR: variable '$var' is not exported"
			return 1
		fi
	done
}

main() {
	if [ -z "${CLOUD_PROVIDER}" ]; then
		echo "ERROR: You must export the CLOUD_PROVIDER variable"
		exit 1
	fi

	local impl_file="${script_dir}/${CLOUD_PROVIDER}/pipeline_impl.sh"
	if [ ! -f "${impl_file}" ]; then
		echo "ERROR: pipeline implementation file not found at ${impl_file}"
		exit 1
	fi
	source "${impl_file}"

	check_commands
	check_envvars

	echo "PIPELINE::SETUP"
	pipeline_setup
	echo "END PIPELINE::SETUP"

	# Run the pipeline
	local step
	for step in vpc_create\
		cluster_create; do
		echo "STEP::${step}"
		run_step "$step"
		echo "END STEP::$step"
	done
}

# Run the step only and only if the implementing function is defined.
#
run_step() {
	local step_name="$1"
	local step_fn="step_${step_name}"

	if declare -F "$step_fn" > /dev/null; then
		eval "$step_fn"
	fi
}

main "$@"
```

Here is the draft implementation to ibmcloud:
```bash
#!/bin/bash

##
# Methods and variables that should be implemented goes below.
##

# List of required commands to run the pipeline.
REQ_COMMANDS="terraform"

# List of required environment variables to run the pipeline.
REQ_ENVVARS="IBMCLOUD_API_KEY IBMCLOUD_USER_ID IBMCLOUD_CLUSTER_NAME "\
"SSH_KEY_NAME PODVM_IMAGE_NAME COS_BUCKET_NAME"

# Run immediately before the pipeline steps.
#
pipeline_setup() {
	_gen_terraform_tfvars
}

# Run after the last pipeline step.
#
#pipeline_teardown() {
#}

# Create the Virtual Private Cluster (VPC)
#
step_vpc_create() {
	pushd "$tf_dir"
	terraform init
	terraform plan
	terraform apply
	popd
}

step_k8s_cluster_create() {
	echo "create the k8s cluster"
}

##
# Internal methods and variables goes below.
##

impl_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Path to terraform files
tf_dir="$(cd "${impl_dir}/../../../ibmcloud/terraform" && pwd)"

_gen_terraform_tfvars() {
	local template_file="${impl_dir}/terraform.tfvars.in"
	local tfvars_file="${tf_dir}/terraform.tfvars"

	# TODO: pass the exact list of variables.
	envsubst < "$template_file" > "${tfvars_file}"

	# Handle option parameters.
	#
	[ -n "$IBMCLOUD_REGION_NAME" ] && \
		echo "region_name=$IBMCLOUD_REGION_NAME" >> "${tfvars_file}"

	#region_name = "<name of an IBM Cloud region>"
	#zone_name = "<name of a zone in your IBM Cloud zone region>"
	#ssh_pub_key = "<your SSH public key>"
	#cos_service_instance_name = "<name of the COS instance to create>"
	#cos_bucket_region = "<name of the region to create the COS bucket in>"
	#floating_ip_name = "<name of the floating IP to create>"
	#image_name = "<name of the image to use for the Kubernetes control plane and worker>"
	#instance_profile_name = "<name of the instance profile to use for the Kubernetes control plane and worker>"
	#primary_security_group_name = "<name of the primary security group to create>"
	#primary_subnet_name = "<name of the primary subnet name to create>"
	#public_gateway_name = "<name of the public gateway name to create>"
	#vpc_name = "<vpc name>"
}
```

**Comment by stevenhorsman** [comment] 2022-10-27 15:30
Hey Wainer,

Thanks so much for thinking about this. On my read through, my thoughts are that it is a little bit complex, but nice and flexible and I don't think you can get the flexibility without a bit of complexity, so I would say we press on with this approach! I know for your example you've pick ibmcloud and aws and that's great and hopefully it's something we can pick up and test the ibmcloud cloud provider internally early on, but did you have thoughts about running this with libvirt with a GHA workflow in this repo?

Thanks!

**Comment by jtumber-ibm** [comment] 2022-10-27 15:53
I also like the approach to try and share code and leave the specifc implementations for each provider separate. Does e2e tests include the creation of the podvm image? Similar to Steve's point be a nice to have for there to be a test that can run without cloud credentials e.g. libvirt version

**Comment by bpradipt** [comment] 2023-03-23 06:17
The initial CI framework with support for azure, ibmcloud, libvirt is already added. Next step is to get access to runners and decide the schedules. Closing this issue as the intended work is complete. 
Please reopen if required.

**Closed by bpradipt** 2023-03-23 06:17 UTC
